server:
  port: 8080

frontend:
  base-url: http://localhost:4200
  url-decoder: http://localhost:9000

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: ${JWT_SECRET}

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: auth-service
              uri: http://localhost:9000
              predicates:
                - Path=/auth/**
            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/admin/users/**
            - id: competition-service
              uri: http://localhost:8085
              predicates:
                - Path=/api/competitions/**
            - id: finance-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/finances/**

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /auth/v3/api-docs
      - name: user-service
        url: /admin/users/v3/api-docs
      - name: competition-service
        url: /api/competitions/v3/api-docs
      - name: finance-service
        url: /api/finances/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka