server:
  port: 8086

spring:
  application:
    name: finance-service
  datasource:
    url: jdbc:mysql://localhost:3306/sports_finance_db?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

frontend:
  url-decoder: http://localhost:9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    instance:
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30