server:
  port: 8083

frontend:
  base-url: http://192.168.1.39:4200
  url-decoder: http://192.168.1.39:9000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USER}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 30MB
  application:
    name: loan-application-service

  datasource:
    url: jdbc:mysql://localhost:3306/DesarrolloWEB?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://192.168.1.39:8761/eureka
    instance:
      lease-renewal-interval-in-seconds: 10
      lease-expiration-duration-in-seconds: 30